- job:
    name: czechlight-clearfog
    parent: run-ci-build-sh-f33
    timeout: 3600
    post-timeout: 600
    vars:
      prepare_git_submodules: true
      zuul_work_dir: "{{ zuul.projects['cesnet-gerrit-czechlight/CzechLight/br2-external'].src_dir }}"
    required-projects: &projects
      - github/buildroot/buildroot
      - CzechLight/dependencies
      - CzechLight/cla-sysrepo
      - CzechLight/gammarus
      - CzechLight/netconf-cli
      - CzechLight/velia
      - CzechLight/lldp-systemd-networkd-sysrepo
      - github/CESNET/libyang
      - github/sysrepo/sysrepo
      - github/CESNET/libnetconf2
      - github/CESNET/Netopeer2
      - github/onqtam/doctest
      - github/docopt/docopt.cpp
      - github/rollbear/trompeloeil
      - github/tplgy/cppcodec
      - github/AmokHuginnsson/replxx
      - github/Kistler-Group/sdbus-cpp

- project:
    check:
      jobs:
        - czechlight-clearfog:
            provides: CzechLight-br2-build-clearfog
            vars:
              artifacts:
                name: br2-work-dir
                glob: 'br2-work-dir-*.tar.zst'
            post-run: ci/post.yaml
            roles:
              - zuul: return-built-artifact

    promote:
      jobs:
        - promote-artifacts:
            timeout: 600
