- job:
    name: czechlight-clearfog
    parent: run-ci-build-sh-f38
    pre-run: ci/pre.yaml
    timeout: 3600
    post-timeout: 600
    vars:
      prepare_git_submodules: true
      zuul_work_dir: "{{ zuul.projects[zuul.project.canonical_hostname + '/CzechLight/br2-external'].src_dir }}"
      git_submodule_dirs: "{{ zuul.projects[zuul.project.canonical_hostname + '/CzechLight/br2-external'].src_dir }}:{{ zuul.projects[zuul.project.canonical_hostname + '/CzechLight/dependencies'].src_dir }}"
      artifacts:
        - name: rauc-image
          glob: 'update.raucb'
        - name: usb-flash-image
          glob: 'usb-flash.img'
    required-projects: &projects
      - github/buildroot/buildroot
      - CzechLight/dependencies
      - CzechLight/cla-sysrepo
      - CzechLight/gammarus
      - CzechLight/netconf-cli
      - CzechLight/velia
      - CzechLight/rousette
      - CzechLight/libyang-cpp
      - CzechLight/sysrepo-cpp
      - CzechLight/libnetconf2-cpp
      - CzechLight/sysrepo-ietf-alarms
      - github/CESNET/libyang
      - github/sysrepo/sysrepo
      - github/CESNET/libnetconf2
      - github/CESNET/Netopeer2
      - github/onqtam/doctest
      - github/rollbear/trompeloeil
      - github/AmokHuginnsson/replxx
      - github/Kistler-Group/sdbus-cpp

- project:
    check:
      jobs:
        - czechlight-clearfog

    promote:
      jobs:
        - promote-artifacts:
            timeout: 600
