- job:
    name: czechlight-clearfog
    parent: run-ci-build-sh
    timeout: 3600
    vars:
      prepare_git_submodules: true
    required-projects: &projects
      - github/buildroot/buildroot
      - CzechLight/dependencies
      - CzechLight/cla-sysrepo
      - CzechLight/gammarus
      - CzechLight/netconf-cli
      - github/CESNET/libyang
      - github/sysrepo/libredblack
      - github/sysrepo/sysrepo
      - github/CESNET/libnetconf2
      - github/CESNET/Netopeer2
      - github/onqtam/doctest
      - github/docopt/docopt.cpp
      - github/gabime/spdlog
      - github/rollbear/trompeloeil
      - github/tplgy/cppcodec
      - github/AmokHuginnsson/replxx
      - github/pybind/pybind11

- job:
    name: czechlight-beagleboneblack
    parent: run-ci-build-sh
    timeout: 3600
    vars:
      prepare_git_submodules: true
    required-projects: *projects

- project:
    check:
      jobs:
        - czechlight-clearfog
        - czechlight-beagleboneblack
