CZECHLIGHT_SEPARATE_BOOT_TMP_TARGET_DIR = $(FS_DIR)/rootfs.czechlight-separate-boot

define CZECHLIGHT_SEPARATE_BOOT_SYMLINK_BOOT
	cd $(TARGET_DIR)/boot
	ln -s . boot
endef

ROOTFS_CZECHLIGHT_SEPARATE_BOOT_PRE_GEN_HOOKS += CZECHLIGHT_SEPARATE_BOOT_SYMLINK_BOOT

ROOTFS_CZECHLIGHT_SEPARATE_BOOT_DEPENDENCIES = host-e2fsprogs

define ROOTFS_CZECHLIGHT_SEPARATE_BOOT_CMD
	rm -f $@
	$(HOST_DIR)/sbin/mkfs.ext2 -d $(TARGET_DIR)/boot -L /boot $@ \
		$(call qstrip,$(CZECHLIGHT_SEPARATE_BOOT_SIZE))
endef

$(eval $(rootfs))
