- hosts: all
  tasks:
    - name: install required packages
      package:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - perl-English
        - perl-IPC-Cmd
        - perl-open
